# Generated by Django 4.2.27 on 2026-07-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_booking_duration_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
