# Generated by Django 4.2.7 on 2026-07-24 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_registrationpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_fee', models.DecimalField(decimal_places=2, default=2500, help_text='Artisan registration fee in NGN (replaces the old hardcoded ARTISAN_REGISTRATION_FEE).', max_digits=10)),
                ('service_fee_flat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_fee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('has_percentage_service_fee', models.BooleanField(default=False, help_text='Off = flat fee (default, recommended). On = percentage of artisan-reported job value.')),
                ('agent_commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('minimum_withdrawal', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('maximum_withdrawal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cancellation_window_hours', models.PositiveIntegerField(default=24, help_text='Hours before scheduled_date a client can cancel without penalty.')),
                ('refund_window_days', models.PositiveIntegerField(default=7)),
                ('supported_payment_gateways', models.JSONField(blank=True, default=list, help_text='e.g. ["paystack"]')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
