# Generated by Django 4.2.7 on 2026-07-25 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_bookingphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artisans_registered', to=settings.AUTH_USER_MODEL),
        ),
    ]
