# Generated by Django 4.2.7 on 2026-07-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_artisanprofile_registered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_late_cancellation',
            field=models.BooleanField(default=False),
        ),
    ]
