# Generated by Django 4.2.7 on 2026-07-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='avg_response_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
