# Generated by Django 4.2.7 on 2026-07-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_artisanprofile_avg_response_minutes_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed', 'in_progress'])), fields=('artisan', 'scheduled_date'), name='unique_active_booking_per_artisan_slot'),
        ),
    ]
