# Generated by Django 4.2.7 on 2026-08-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_booking_unique_active_booking_per_artisan_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_language', models.CharField(max_length=10)),
                ('target_language', models.CharField(max_length=10)),
                ('source_text_hash', models.CharField(db_index=True, max_length=64)),
                ('source_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source_language', 'target_language', 'source_text_hash'], name='core_transl_source__45d9ac_idx')],
                'unique_together': {('source_language', 'target_language', 'source_text_hash')},
            },
        ),
    ]
