# Generated by Django 4.2.7 on 2026-08-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_translationcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='material_icon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
