# Generated by Django 4.2.7 on 2026-08-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_booking_live_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_request_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('client', 'client_request_id'), name='unique_client_request_id_per_client'),
        ),
    ]
