# Generated by Django 4.2.7 on 2026-08-29 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_country_code_remove_country_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_category_category_type_businessprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(choices=[('agent_created', 'Created agent'), ('agent_approved', 'Approved agent'), ('agent_rejected', 'Rejected agent'), ('agent_suspended', 'Suspended agent'), ('agent_reactivated', 'Reactivated agent'), ('agent_dismissed', 'Dismissed agent'), ('artisan_registered', 'Registered artisan'), ('artisan_verified', 'Completed verification'), ('artisan_verification_rejected', 'Rejected verification')], max_length=40)),
                ('target_repr', models.CharField(blank=True, max_length=150)),
                ('target_role', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_log_entries', to=settings.AUTH_USER_MODEL)),
                ('lga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_log_entries', to='locations.lga')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_log_entries', to='locations.state')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_log_targeted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state', '-created_at'], name='core_activi_state_i_a38816_idx')],
            },
        ),
    ]
