# Generated by Django 4.2.7 on 2026-09-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('agent_created', 'Created agent'), ('agent_approved', 'Approved agent'), ('agent_rejected', 'Rejected agent'), ('agent_suspended', 'Suspended agent'), ('agent_reactivated', 'Reactivated agent'), ('agent_dismissed', 'Dismissed agent'), ('artisan_registered', 'Registered artisan'), ('business_registered', 'Registered business'), ('artisan_verified', 'Completed verification'), ('artisan_verification_rejected', 'Rejected verification'), ('report_filed', 'Filed report'), ('report_investigating', 'Marked report investigating'), ('report_resolved', 'Resolved report'), ('report_dismissed', 'Dismissed report'), ('coordinator_created', 'Created coordinator'), ('coordinator_suspended', 'Suspended coordinator'), ('coordinator_reactivated', 'Reactivated coordinator'), ('coordinator_dismissed', 'Dismissed coordinator'), ('business_verified', 'Completed business verification'), ('business_verification_rejected', 'Rejected business verification')], max_length=40),
        ),
    ]
