# Generated by Django 4.2.7 on 2026-09-08 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_activitylog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTaxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_slug', models.SlugField(max_length=60, unique=True)),
                ('service_label', models.CharField(help_text="Human-readable, e.g. 'Electrical Installation'", max_length=100)),
                ('profession', models.CharField(help_text="e.g. 'electrician', 'car_rental_business', 'doctor'", max_length=100)),
                ('provider_type', models.CharField(choices=[('artisan', 'Artisan'), ('business', 'Business'), ('professional', 'Professional')], max_length=20)),
                ('group', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='The real, searchable Category this profession resolves to. Leave blank until one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxonomy_rows', to='core.category')),
            ],
            options={
                'verbose_name': 'Service taxonomy row',
                'verbose_name_plural': 'Service taxonomy',
                'ordering': ['group', 'profession', 'service_slug'],
            },
        ),
    ]
