# Generated by Django 4.2.7 on 2026-09-16 10:32

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_seed_service_taxonomy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrequest',
            name='document_image_1',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\DELL\\mahiapp\\smahi_backend\\private_media'), upload_to='verification_documents/'),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='document_image_2',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\DELL\\mahiapp\\smahi_backend\\private_media'), upload_to='verification_documents/'),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='document_image_3',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\DELL\\mahiapp\\smahi_backend\\private_media'), upload_to='verification_documents/'),
        ),
    ]
