# Generated by Django 5.2.13 on 2026-09-17 13:08

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_alter_verificationrequest_document_image_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationrequest",
            name="document_image_1",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="/home/smahi1/smahi_backend/private_media"
                ),
                upload_to="verification_documents/",
            ),
        ),
        migrations.AlterField(
            model_name="verificationrequest",
            name="document_image_2",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="/home/smahi1/smahi_backend/private_media"
                ),
                upload_to="verification_documents/",
            ),
        ),
        migrations.AlterField(
            model_name="verificationrequest",
            name="document_image_3",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="/home/smahi1/smahi_backend/private_media"
                ),
                upload_to="verification_documents/",
            ),
        ),
    ]
