# Generated by Django 4.2.27 on 2026-09-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_verificationrequest_document_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('agent_created', 'Created agent'), ('agent_approved', 'Approved agent'), ('agent_rejected', 'Rejected agent'), ('agent_suspended', 'Suspended agent'), ('agent_reactivated', 'Reactivated agent'), ('agent_dismissed', 'Dismissed agent'), ('artisan_registered', 'Registered artisan'), ('business_registered', 'Registered business'), ('registration_fee_collected', 'Collected registration fee'), ('artisan_verified', 'Completed verification'), ('artisan_verification_rejected', 'Rejected verification'), ('report_filed', 'Filed report'), ('report_investigating', 'Marked report investigating'), ('report_resolved', 'Resolved report'), ('report_dismissed', 'Dismissed report'), ('coordinator_created', 'Created coordinator'), ('coordinator_suspended', 'Suspended coordinator'), ('coordinator_reactivated', 'Reactivated coordinator'), ('coordinator_dismissed', 'Dismissed coordinator'), ('business_verified', 'Completed business verification'), ('business_verification_rejected', 'Rejected business verification'), ('registered_user_updated', 'Updated registered account'), ('registered_user_deactivated', 'Deactivated registered account'), ('agent_reassigned', 'Reassigned agent to a different coordinator'), ('client_assigned', 'Assigned client to an agent')], max_length=40),
        ),
    ]
