# Generated by Django 4.2.27 on 2026-09-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_activitylog_action'),
        ('core', '0029_alter_verificationrequest_document_image_1_and_more'),
    ]

    operations = [
    ]
