# Generated by Django 4.2.27 on 2026-09-24 08:49
#
# Django's autodetector also proposed AlterField ops on VerificationRequest's
# document_image_* fields here — an artifact of FileSystemStorage baking this
# machine's own absolute local path into the field's deconstructed state
# (core/storage.py's private_media_storage), not a real model change. Left
# out deliberately; only PortfolioItem is new.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0030_merge_20260919_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('kind', models.CharField(choices=[('service', 'Service'), ('for_sale', 'For sale')], default='service', max_length=10)),
                ('price_label', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(limit_choices_to={'role__in': ['artisan', 'business']}, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
