# Generated by Django 4.2.7 on 2026-08-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='original_language',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
