# Generated by Django 4.2.7 on 2026-07-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('artisan', 'Artisan'), ('agent', 'Agent'), ('state_coordinator', 'State Coordinator'), ('admin', 'Admin')], default='client', max_length=20),
        ),
    ]
