# Generated by Django 4.2.7 on 2026-07-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_fee_paid',
            field=models.BooleanField(default=False),
        ),
    ]
