# Generated by Django 4.2.7 on 2026-08-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ha', 'Hausa'), ('ar', 'Arabic'), ('fr', 'French'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('de', 'German'), ('it', 'Italian'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('tr', 'Turkish'), ('sw', 'Swahili'), ('yo', 'Yoruba'), ('ig', 'Igbo')], default='', max_length=10),
        ),
    ]
