# Generated by Django 4.2.7 on 2026-08-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_request_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
