# Generated by Django 4.2.7 on 2026-08-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('artisan', 'Artisan'), ('business', 'Business'), ('agent', 'Agent'), ('state_coordinator', 'State Coordinator'), ('admin', 'Admin')], default='client', max_length=20),
        ),
    ]
