# Generated by Django 4.2.7 on 2026-08-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_role'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('account_status__in', ['active', 'suspended']), ('role', 'state_coordinator')), fields=('state',), name='unique_active_coordinator_per_state'),
        ),
    ]
