# Generated by Django 4.2.7 on 2026-08-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_role'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'state_coordinator'), models.Q(('account_status', 'dismissed'), _negated=True)), fields=('state',), name='unique_active_coordinator_per_state'),
        ),
    ]
