# Generated by Django 4.2.7 on 2026-08-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_unique_active_coordinator_per_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='serial_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('dismissed', 'Dismissed'), ('pending_approval', 'Pending Approval'), ('rejected', 'Rejected')], default='active', max_length=20),
        ),
    ]
