# Generated by Django 4.2.7 for the referral-network rollout — backfills
# the two things pre-existing accounts can't get through the normal
# creation/approval paths:
#
#   1. referral_code for every Coordinator/Agent who already holds a role
#      seat (there is no pending_approval step in their history to mint it
#      from). Coordinators -> SMAHI-<STATE>-XXXX, Agents -> SMAHI-AG-XXXX.
#      Codes are minted UNIQUE (retry on collision) and never overwritten.
#   2. sponsor_coordinator for every Agent whose state has a current active/
#      suspended Coordinator — the registration chain Coordinator->Agent had
#      no explicit FK until now, and state-scoping was the only link. Agents
#      in a state with no standing coordinator stay unlinked (fine — the
#      effective_coordinator helper resolves the state's coordinator
#      dynamically for them).
#
# Backward-compatible by construction: every new field is nullable, and the
# migration metadata stays on the accounts app exclusively (core's
# ArtisanProfile.registered_by already carried the Agent->ServiceProvider
# leg before this feature).
import secrets

from django.db import migrations

REFERRAL_BRAND = 'SMAHI'
AGENT_TAG = 'AG'
ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'
# Matches core.permissions.IsAgent's seat rule exactly: an agent only ever
# had a real working account once 'active'; 'suspended' kept their row but
# not their working seat. Only 'active' agents get a code here.
# Coordinators occupy their seat while 'active' OR 'suspended'
# (unique_active_coordinator_per_state), so both get codes.
COORDINATOR_SEAT_STATUSES = ('active', 'suspended')


def _code_tail():
    return ''.join(secrets.choice(ALPHABET) for _ in range(4))


def _unique_code(User, tag):
    while True:
        code = f'{REFERRAL_BRAND}-{tag}-{_code_tail()}'
        if not User.objects.filter(referral_code__iexact=code).exists():
            return code


def backfill_referral_data(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(referral_code__isnull=True, referral_code='').update(referral_code=None)

    # Coordinators first — they're the top of the chain, so agents can
    # link to them right after.
    for coord in User.objects.filter(role='state_coordinator', account_status__in=COORDINATOR_SEAT_STATUSES):
        if coord.referral_code:
            continue
        state = coord.state
        tag = (state.state_code or state.name[:3]).upper() if state else 'ST'
        coord.referral_code = _unique_code(User, tag)
        coord.save(update_fields=['referral_code'])

    # Agents — mint only for actually-approved agents, and link each to the
    # standing Coordinator of their state (the pre-referral-inherited link).
    for agent in User.objects.filter(role='agent', account_status='active'):
        update_fields = []
        if not agent.referral_code:
            agent.referral_code = _unique_code(User, AGENT_TAG)
            update_fields.append('referral_code')
        if not agent.sponsor_coordinator_id and agent.state_id:
            coord = User.objects.filter(
                role='state_coordinator', state_id=agent.state_id,
                account_status__in=COORDINATOR_SEAT_STATUSES,
            ).order_by('-created_at').first()
            if coord:
                agent.sponsor_coordinator = coord
                update_fields.append('sponsor_coordinator')
        if update_fields:
            agent.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_referral_code_user_sponsor_agent_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_referral_data, migrations.RunPython.noop),
    ]