# Generated by Django 4.2.27 on 2026-09-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('artisan', 'Artisan'), ('business', 'Business'), ('agent', 'Agent'), ('state_coordinator', 'State Coordinator'), ('admin', 'Admin')], db_index=True, default='client', max_length=20),
        ),
    ]
