# Generated by Django 4.2.7 on 2026-08-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('booking_created', 'Booking Created'), ('booking_confirmed', 'Booking Confirmed'), ('booking_started', 'Booking Started'), ('booking_completed', 'Booking Completed'), ('booking_cancelled', 'Booking Cancelled'), ('service_fee_requested', 'Service Fee Requested'), ('service_fee_paid', 'Service Fee Paid'), ('review_submitted', 'Review Submitted'), ('verification_approved', 'Verification Approved'), ('verification_rejected', 'Verification Rejected'), ('wallet_credited', 'Wallet Credited'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_rejected', 'Withdrawal Rejected'), ('dispute_created', 'Dispute Created'), ('dispute_resolved', 'Dispute Resolved'), ('agent_pending_approval', 'Agent Pending Approval')], max_length=40),
        ),
    ]
